### ISSUE TITLE
Prefix keeps default "remote" 

### ISSUE THREAD

**Issue by vahaldor** [custom-components/remote_homeassistant#189]
If I need to add some sensors from the remote HA, I need to remember to change default "remote" filled in the prefix form with mine "hasslivingroom_". Doing it once in a month or half a year means all remote sensors, services etc. are not available because they are added to my HA with "remote" prefix. I think that the integratoin could remember my last settings as it does with checked boxes in the other sections of the configuration.

**Comment by lukas-hetzenecker** [comment]
fixed in #198

**Comment by vahaldor** [comment]
Sorry, it is not fixed.

How I submit it by clicking on submit (that goes to another dialog):
<img width="277" alt="image" src="https://user-images.githubusercontent.com/6329152/202250455-12b65215-89d8-4310-bbbe-b99083bc5bc3.png">

How it looks when I reopen the dialog by clicking on 'configure' in the integrations list:
<img width="272" alt="image" src="https://user-images.githubusercontent.com/6329152/202250638-089b0507-2eea-4178-bad3-d11e3f2d572e.png">

**Comment by lukas-hetzenecker** [comment]
FYI, the change is part of release 3.8.
