### ISSUE TITLE
Home Assistant 2023.7.1 update breaks remote_homeassistant

### ISSUE THREAD

**Issue by sag007** [custom-components/remote_homeassistant#240]
Hey Guys,

I applied the latest update to my HA installs, one at home and one at our farm and now I get the error;
2023.7.1
ImportError: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core'

Regards,

Nathan

**Comment by sgurgul** [comment]
I confim, same on my side
Error occurred loading flow for integration remote_homeassistant: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)

The only update is that the issue occurs in 2023.7.0 already and applies to 2023.7.1 as well.

**Comment by lukas-hetzenecker** [comment]
Latest release of this integration form yesterday should fix this issue

**Comment by sibbl** [comment]
I updated to 2023.7.0 and today to 2023.7.1. After a reboot, I updated remote_homeassistant via HACS.

A reboot via HA frontend then was not possible due to the `cannot import name 'SERVICE_CALL_LIMIT' from .const` - which is different from the error above.

Everything turned out well after rebooting via the CLI which the Hass Supervisor provides (run `core reboot` there).

**Comment by sag007** [comment]
Hey Guys,

A reboot with the latest version of everything didnt resolve the issues. As per mchangsp post in another thread i had to do the following;

Go to the file custom_components/remote_homeassistant/proxy services.py
Comment out line 5: # from homeassistant.core import SERVICE_CALL_LIMIT
insert a new line: SERVICE_CALL_LIMIT = 10
Reboot your HA 2023.7 instance

Now everything works again.

Thanks mchangsp
